from __future__ import annotations

import contextlib
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

from .config import Settings
from .constants import LEGACY_TABLE_NAMES, LOG_PREFIX, TABLE_NAME
from .iputil import collapse_sources_for_nft
from .state import State


def _nft_set_name(lport: int) -> str:
    return f"src_{lport}"


def render_nft(settings: Settings, state: State) -> str:
    local_ip = detect_local_ip()
    lines: list[str] = [
        "#!/usr/sbin/nft -f",
        "",
        "# Generated by nft-forward. Do not edit by hand.",
        f"define LOCAL_IP = {local_ip}",
        "",
        f"table ip {TABLE_NAME} {{",
    ]
    rules = state.rules()
    effective: dict[int, list[str]] = {}
    for rule in rules:
        sources = collapse_sources_for_nft(state.effective_sources_for_rule(rule))
        effective[rule.lport] = sources
        if not rule.open_access and sources:
            lines += [
                f"    set {_nft_set_name(rule.lport)} {{",
                "        type ipv4_addr",
                "        flags interval",
                "        elements = { " + ", ".join(sources) + " }",
                "    }",
                "",
            ]
    guarded = [r for r in rules if not r.open_access]
    if guarded:
        lines += [
            "    chain source_guard {",
        ]
        for rule in guarded:
            sources = effective[rule.lport]
            prefix = f"{LOG_PREFIX}port={rule.lport} "
            if sources:
                set_name = _nft_set_name(rule.lport)
                lines += [
                    f'        ip saddr != @{set_name} tcp dport {rule.lport} limit rate 12/minute burst 20 packets log prefix "{prefix}" drop',
                    f'        ip saddr != @{set_name} udp dport {rule.lport} limit rate 12/minute burst 20 packets log prefix "{prefix}" drop',
                ]
            else:
                lines += [
                    f'        tcp dport {rule.lport} limit rate 12/minute burst 20 packets log prefix "{prefix}" drop',
                    f'        udp dport {rule.lport} limit rate 12/minute burst 20 packets log prefix "{prefix}" drop',
                ]
        lines += ["    }", ""]
    lines += [
        "    chain prerouting {",
        "        type nat hook prerouting priority -100; policy accept;",
    ]
    if guarded:
        lines += ["        jump source_guard"]
    for rule in rules:
        lines.append("")
        lines.append(f"        # 转发: 本机:{rule.lport} -> {rule.dest_ip}:{rule.dest_port}")
        if rule.note:
            lines.append(f"        # 备注: {rule.note}")
        if rule.open_access:
            src_match = ""
        elif effective[rule.lport]:
            src_match = f"ip saddr @{_nft_set_name(rule.lport)} "
        else:
            lines.append("        # 当前没有有效允许来源，保持关闭。")
            continue
        lines.append(f"        {src_match}tcp dport {rule.lport} dnat to {rule.dest_ip}:{rule.dest_port}")
        lines.append(f"        {src_match}udp dport {rule.lport} dnat to {rule.dest_ip}:{rule.dest_port}")
    lines += [
        "    }",
        "",
        "    chain postrouting {",
        "        type nat hook postrouting priority 100; policy accept;",
    ]
    for rule in rules:
        lines += [
            "",
            f"        # 回源: 发往 {rule.dest_ip}:{rule.dest_port} 的已 DNAT 流量, SNAT 为本机 IP",
            f"        ip daddr {rule.dest_ip} tcp dport {rule.dest_port} ct status dnat snat to $LOCAL_IP",
            f"        ip daddr {rule.dest_ip} udp dport {rule.dest_port} ct status dnat snat to $LOCAL_IP",
        ]
    lines += ["    }", "}"]
    return "\n".join(lines) + "\n"


def detect_local_ip() -> str:
    for cmd in (
        ["ip", "route", "get", "1.1.1.1"],
        ["hostname", "-I"],
    ):
        try:
            proc = subprocess.run(cmd, text=True, capture_output=True, timeout=3)
        except (OSError, subprocess.TimeoutExpired):
            continue
        text = proc.stdout.strip()
        if " src " in text:
            return text.split(" src ", 1)[1].split()[0]
        if text:
            return text.split()[0]
    return "127.0.0.1"


def validate_nft(text: str) -> tuple[bool, str]:
    if shutil.which("nft") is None:
        return True, "nft not installed; skipped validation"
    # `nft -c` checks against the current live ruleset. Reusing the managed
    # table name can produce false "File exists" errors for unchanged sets.
    validation_table = f"{TABLE_NAME}_check_{os.getpid()}"
    check_text = text.replace(f"table ip {TABLE_NAME} {{", f"table ip {validation_table} {{", 1)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False) as fh:
        fh.write(check_text)
        tmp = fh.name
    try:
        proc = subprocess.run(["nft", "-c", "-f", tmp], text=True, capture_output=True, timeout=10)
        return proc.returncode == 0, proc.stderr.strip() or proc.stdout.strip()
    except (OSError, subprocess.TimeoutExpired) as exc:
        return False, str(exc)
    finally:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def table_exists(table_name: str) -> bool:
    try:
        proc = subprocess.run(
            ["nft", "list", "table", "ip", table_name],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return proc.returncode == 0


def run_nft_batch(text: str) -> subprocess.CompletedProcess[str]:
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False) as fh:
        fh.write(text)
        tmp = fh.name
    try:
        return subprocess.run(["nft", "-f", tmp], text=True, capture_output=True, timeout=10)
    finally:
        try:
            os.unlink(tmp)
        except OSError:
            pass


@contextlib.contextmanager
def apply_lock(settings: Settings):
    if not settings.paths:
        yield
        return
    lock_path = settings.paths.state_db.parent / "apply.lock"
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    with lock_path.open("a+") as lock_file:
        try:
            import fcntl

            fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
        except (ImportError, OSError):
            pass
        try:
            yield
        finally:
            try:
                import fcntl

                fcntl.flock(lock_file.fileno(), fcntl.LOCK_UN)
            except (ImportError, OSError):
                pass


def write_config_atomically(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_name = ""
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            dir=str(path.parent),
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as fh:
            fh.write(text)
            tmp_name = fh.name
        os.replace(tmp_name, path)
    finally:
        if tmp_name:
            try:
                os.unlink(tmp_name)
            except FileNotFoundError:
                pass


def write_and_apply(settings: Settings, state: State, apply: bool = True) -> str:
    if not settings.paths:
        raise RuntimeError("settings paths not loaded")
    with apply_lock(settings):
        text = render_nft(settings, state)
        ok, message = validate_nft(text)
        if not ok:
            raise RuntimeError(f"nft validation failed: {message}")
        write_config_atomically(settings.paths.nft_conf, text)
        if apply and shutil.which("nft"):
            apply_text = text
            if table_exists(TABLE_NAME):
                apply_text = f"delete table ip {TABLE_NAME}\n" + text
            proc = run_nft_batch(apply_text)
            if proc.returncode != 0:
                raise RuntimeError(proc.stderr.strip() or "nft apply failed")
            for legacy_table in LEGACY_TABLE_NAMES:
                subprocess.run(["nft", "flush", "table", "ip", legacy_table], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                subprocess.run(["nft", "delete", "table", "ip", legacy_table], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return message or "ok"
