from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from pathlib import Path

from .config import Settings
from .constants import LOG_PREFIX, TABLE_NAME
from .state import State


def _nft_set_name(lport: int) -> str:
    return f"src_{lport}"


def render_nft(settings: Settings, state: State) -> str:
    local_ip = detect_local_ip()
    lines: list[str] = [
        "#!/usr/sbin/nft -f",
        "",
        "# Generated by nft-forward. Do not edit by hand.",
        f"define LOCAL_IP = {local_ip}",
        "",
        f"table ip {TABLE_NAME} {{",
    ]
    rules = state.rules()
    effective: dict[int, list[str]] = {}
    for rule in rules:
        sources = state.effective_sources_for_rule(rule)
        effective[rule.lport] = sources
        if not rule.open_access and sources:
            lines += [
                f"    set {_nft_set_name(rule.lport)} {{",
                "        type ipv4_addr",
                "        flags interval",
                "        elements = { " + ", ".join(sources) + " }",
                "    }",
                "",
            ]
    guarded = [r for r in rules if not r.open_access]
    if guarded:
        lines += [
            "    chain source_guard {",
            "        type filter hook prerouting priority -101; policy accept;",
        ]
        for rule in guarded:
            sources = effective[rule.lport]
            prefix = f"{LOG_PREFIX}port={rule.lport} "
            if sources:
                set_name = _nft_set_name(rule.lport)
                lines += [
                    f'        ip saddr != @{set_name} tcp dport {rule.lport} limit rate 12/minute burst 20 packets log prefix "{prefix}" drop',
                    f'        ip saddr != @{set_name} udp dport {rule.lport} limit rate 12/minute burst 20 packets log prefix "{prefix}" drop',
                ]
            else:
                lines += [
                    f'        tcp dport {rule.lport} limit rate 12/minute burst 20 packets log prefix "{prefix}" drop',
                    f'        udp dport {rule.lport} limit rate 12/minute burst 20 packets log prefix "{prefix}" drop',
                ]
        lines += ["    }", ""]
    lines += [
        "    chain prerouting {",
        "        type nat hook prerouting priority -100; policy accept;",
    ]
    for rule in rules:
        lines.append("")
        lines.append(f"        # 转发: 本机:{rule.lport} -> {rule.dest_ip}:{rule.dest_port}")
        if rule.note:
            lines.append(f"        # 备注: {rule.note}")
        if rule.open_access:
            src_match = ""
        elif effective[rule.lport]:
            src_match = f"ip saddr @{_nft_set_name(rule.lport)} "
        else:
            lines.append("        # 当前没有有效允许来源，保持关闭。")
            continue
        lines.append(f"        {src_match}tcp dport {rule.lport} dnat to {rule.dest_ip}:{rule.dest_port}")
        lines.append(f"        {src_match}udp dport {rule.lport} dnat to {rule.dest_ip}:{rule.dest_port}")
    lines += [
        "    }",
        "",
        "    chain postrouting {",
        "        type nat hook postrouting priority 100; policy accept;",
    ]
    for rule in rules:
        lines += [
            "",
            f"        # 回源: 发往 {rule.dest_ip}:{rule.dest_port} 的已 DNAT 流量, SNAT 为本机 IP",
            f"        ip daddr {rule.dest_ip} tcp dport {rule.dest_port} ct status dnat snat to $LOCAL_IP",
            f"        ip daddr {rule.dest_ip} udp dport {rule.dest_port} ct status dnat snat to $LOCAL_IP",
        ]
    lines += ["    }", "}"]
    return "\n".join(lines) + "\n"


def detect_local_ip() -> str:
    for cmd in (
        ["ip", "route", "get", "1.1.1.1"],
        ["hostname", "-I"],
    ):
        try:
            proc = subprocess.run(cmd, text=True, capture_output=True, timeout=3)
        except (OSError, subprocess.TimeoutExpired):
            continue
        text = proc.stdout.strip()
        if " src " in text:
            return text.split(" src ", 1)[1].split()[0]
        if text:
            return text.split()[0]
    return "127.0.0.1"


def validate_nft(text: str) -> tuple[bool, str]:
    if shutil.which("nft") is None:
        return True, "nft not installed; skipped validation"
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False) as fh:
        fh.write(text)
        tmp = fh.name
    try:
        proc = subprocess.run(["nft", "-c", "-f", tmp], text=True, capture_output=True, timeout=10)
        return proc.returncode == 0, proc.stderr.strip() or proc.stdout.strip()
    except (OSError, subprocess.TimeoutExpired) as exc:
        return False, str(exc)
    finally:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def write_and_apply(settings: Settings, state: State, apply: bool = True) -> str:
    if not settings.paths:
        raise RuntimeError("settings paths not loaded")
    text = render_nft(settings, state)
    ok, message = validate_nft(text)
    if not ok:
        raise RuntimeError(f"nft validation failed: {message}")
    settings.paths.nft_conf.parent.mkdir(parents=True, exist_ok=True)
    tmp = settings.paths.nft_conf.with_suffix(".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(settings.paths.nft_conf)
    if apply and shutil.which("nft"):
        subprocess.run(["nft", "flush", "table", "ip", TABLE_NAME], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        subprocess.run(["nft", "delete", "table", "ip", TABLE_NAME], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        proc = subprocess.run(["nft", "-f", str(settings.paths.nft_conf)], text=True, capture_output=True, timeout=10)
        if proc.returncode != 0:
            raise RuntimeError(proc.stderr.strip() or "nft apply failed")
    return message or "ok"
