#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"
INSTALL_DIR="/opt/nft-forward"
CONFIG_DIR="/etc/nft-forward"
STATE_DIR="/var/lib/nft-forward"
LOG_DIR="/var/log/nft-forward"

if [[ ${EUID} -ne 0 ]]; then
    echo "Please run as root." >&2
    exit 1
fi

if [[ -f /etc/os-release ]]; then
    . /etc/os-release
else
    ID=unknown
fi

if [[ "${ID}" != "debian" && "${ID}" != "ubuntu" ]]; then
    echo "Warning: this installer is tested on Debian/Ubuntu; attempting a best-effort Linux install." >&2
fi

install_relay_packages() {
    local need_pkg=()
    for cmd in python3 nft ssh systemctl sysctl; do
        command -v "${cmd}" >/dev/null 2>&1 || need_pkg+=("${cmd}")
    done
    if ((${#need_pkg[@]} == 0)); then
        return 0
    fi

    if command -v apt-get >/dev/null 2>&1; then
        apt-get update -y
        DEBIAN_FRONTEND=noninteractive apt-get install -y \
            -o Dpkg::Options::=--force-confdef \
            -o Dpkg::Options::=--force-confold \
            python3 nftables openssh-client systemd procps
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y python3 nftables openssh-clients systemd procps-ng
    elif command -v yum >/dev/null 2>&1; then
        yum install -y python3 nftables openssh-clients systemd procps-ng
    elif command -v pacman >/dev/null 2>&1; then
        pacman -Sy --noconfirm python nftables openssh systemd procps-ng
    else
        echo "Missing required commands: ${need_pkg[*]}" >&2
        echo "Install Python 3, nftables, OpenSSH client, systemd, and procps/sysctl, then rerun this script." >&2
        exit 1
    fi
}

enable_ipv4_forwarding() {
    local conf_file="/etc/sysctl.d/99-niftgate-ip-forward.conf"
    echo "Enabling IPv4 forwarding for relay traffic..."

    if [[ -d /etc/sysctl.d ]]; then
        printf '%s\n' "net.ipv4.ip_forward=1" >"${conf_file}"
        chmod 0644 "${conf_file}" || true
    else
        touch /etc/sysctl.conf
        if grep -Eq '^[[:space:]]*#?[[:space:]]*net\.ipv4\.ip_forward[[:space:]]*=' /etc/sysctl.conf; then
            sed -i.bak -E 's/^[[:space:]]*#?[[:space:]]*net\.ipv4\.ip_forward[[:space:]]*=.*/net.ipv4.ip_forward=1/' /etc/sysctl.conf
        else
            printf '\n%s\n' "net.ipv4.ip_forward=1" >>/etc/sysctl.conf
        fi
    fi

    if command -v sysctl >/dev/null 2>&1; then
        sysctl -w net.ipv4.ip_forward=1 >/dev/null || true
        if [[ -f "${conf_file}" ]]; then
            sysctl -p "${conf_file}" >/dev/null 2>&1 || true
        else
            sysctl -p /etc/sysctl.conf >/dev/null 2>&1 || true
        fi
    elif [[ -w /proc/sys/net/ipv4/ip_forward ]]; then
        printf '%s\n' "1" >/proc/sys/net/ipv4/ip_forward || true
    fi

    if [[ "$(cat /proc/sys/net/ipv4/ip_forward 2>/dev/null || printf '%s' unknown)" != "1" ]]; then
        echo "Warning: IPv4 forwarding could not be confirmed; check net.ipv4.ip_forward manually." >&2
    fi
}

install_relay_packages
enable_ipv4_forwarding

mkdir -p "${INSTALL_DIR}" "${CONFIG_DIR}" "${STATE_DIR}" "${LOG_DIR}" /etc/nftables.d
cp -a "${PROJECT_DIR}/." "${INSTALL_DIR}/"
chmod +x "${INSTALL_DIR}/bin/nft.sh" "${INSTALL_DIR}/scripts/"*.sh "${INSTALL_DIR}/scripts/update_ip_cache.py" 2>/dev/null || true

install -m 0755 "${INSTALL_DIR}/bin/nft.sh" /usr/local/bin/nft.sh
install -m 0755 "${INSTALL_DIR}/scripts/relay_restricted_command.sh" /usr/local/bin/nft-forward-relay-command

if [[ ! -f "${CONFIG_DIR}/config.json" ]]; then
    install -m 0600 "${INSTALL_DIR}/config/config.example.json" "${CONFIG_DIR}/config.json"
    echo "Created ${CONFIG_DIR}/config.json; edit SSH/DDNS settings before enabling remote integrations."
fi

if [[ ! -f /etc/nftables.conf ]]; then
    cat >/etc/nftables.conf <<'NFTCONF'
#!/usr/sbin/nft -f
flush ruleset
include "/etc/nftables.d/*.conf"
NFTCONF
elif ! grep -qF 'include "/etc/nftables.d/*.conf"' /etc/nftables.conf; then
    printf '\ninclude "/etc/nftables.d/*.conf"\n' >> /etc/nftables.conf
fi

NFT_FORWARD_CONFIG="${CONFIG_DIR}/config.json" /usr/local/bin/nft.sh init-db
if [[ -f /etc/nftables.d/port-forward.conf ]] && ! grep -qF '# Generated by nft-forward.' /etc/nftables.d/port-forward.conf; then
    NFT_FORWARD_CONFIG="${CONFIG_DIR}/config.json" /usr/local/bin/nft.sh import-legacy /etc/nftables.d/port-forward.conf || true
fi
NFT_FORWARD_CONFIG="${CONFIG_DIR}/config.json" /usr/local/bin/nft.sh apply --no-apply || true

install -m 0644 "${INSTALL_DIR}/services/nft-forward-blocklog.service" /etc/systemd/system/
install -m 0644 "${INSTALL_DIR}/services/nft-forward-sshlog.service" /etc/systemd/system/
install -m 0644 "${INSTALL_DIR}/services/nft-forward-ddns.service" /etc/systemd/system/
install -m 0644 "${INSTALL_DIR}/services/nft-forward-ddns.timer" /etc/systemd/system/
systemctl daemon-reload
systemctl enable --now nft-forward-blocklog.service || true
systemctl enable --now nft-forward-sshlog.service || true
systemctl enable --now nft-forward-ddns.timer || true
systemctl enable --now nftables || true

cat <<EOF

Relay installation complete.

Next steps:
1. Edit ${CONFIG_DIR}/config.json
2. Add the exit node public key to /root/.ssh/authorized_keys like:
   command="/usr/local/bin/nft-forward-relay-command",no-agent-forwarding,no-X11-forwarding,no-pty ssh-ed25519 AAAA...
3. Run: nft.sh status

EOF
